### ISSUE TITLE
Trouble if real dataset (from sensors) is fed to algorithm

### ISSUE THREAD

**Issue by YuriiHordiienko1987** [BenjaminNavarro/ellipsoid-fit#1]
Hello!
I need to implement ellipsoid-fit library into my C/C++ project, but faced with a problem.
Using the ellipsoid-fit lib I constantly was comparing the _center_ and _radii_ values between ellipsoid-fit lib and Matlab [origin](https://www.mathworks.com/matlabcentral/fileexchange/24693-ellipsoid-fit). During a long time I was not getting the same _radii_ values, where the coordinates of the _center_ was absolutely right. I have found that the problem was in this equation:
`auto u = (D.transpose() * D).bdcSvd(Eigen::ComputeFullU | Eigen::ComputeFullV).solve(D.transpose() * d2).eval(); // solution to the normal equations`
If that string is replaced by the next:
	`auto u1 = (D.transpose() * D).eval();`
	`auto u2 = (D.transpose() * d2).eval();`
	`auto u = (u1.inverse() * u2).eval();`
the _center_ and _radii_ in Matlab and ellipsoid-fit lib become similar.
**Then I made a conclusion: according to the [example](https://github.com/BenjaminNavarro/ellipsoid-fit/tree/master/apps/fitting_example), my suggested string above doesn't matter, but if we are using real dataset, _radii_ and _center_ don't match with Matlab results properly!**

But, the investigation didn't finish yet. If I have made my changes the 1x3 matrix of _radii_ has mixed x,y,z, to be tolerance x was at y, y was at z, z was at x positions respectively. Further, I clarified that the next issue was in the string:
`Eigen::EigenSolver<Eigen::Matrix3d> solver(R.block<3,3>(0,0) / -R(3,3));`
At this step the "solver" gets a wrong x,y,z order. By the way, the matrix R in Matlab and ellipsoid-fit lib had the same values absolutely. The `solver.eigenvalues()` has already mixed order of x,y,z.
I tried different approaches and everything to transform the matrix another way but, I have not found the solution to fix that. 

Please, try to use my suggestions to fix this issue or find out such behaviour. Thanks!

**Comment by BenjaminNavarro** [comment]
To add a bit to this, concerning
```
[ evecs, evals ] = eig( R( 1:3, 1:3 ) / -R( 4, 4 ) );
radii = sqrt( 1 ./ diag( abs( evals ) ) );
```
translated to
```
Eigen::EigenSolver<Eigen::Matrix3d> solver(R.block<3,3>(0,0) / -R(3,3));
params.radii = solver.eigenvalues().cwiseAbs().cwiseInverse().cwiseSqrt();

```
what I find strange is that both methods (`eig()` and `solver.eigenvalues()`) are documented as providing the eigen values in any particular order:
* [Eigen](https://eigen.tuxfamily.org/dox/classEigen_1_1EigenSolver.html#a114189009e42f5e03372a7a3dfa33b97)
* [Matlab](https://www.mathworks.com/help/matlab/ref/eig.html) (see section Sorted Eigenvalues and Eigenvectors)

So I wonder if the Matlab algorithm is itself correct or if it works by chance. Maybe it fails in some cases? I need to get a hand on a license to test it more thoroughly.

**Comment by YuriiHordiienko1987** [comment]
Yes, I think good idea to use licensed software. 
Of course, I picked up the matrix `R.block<3,3>(0,0) / -R(3,3)` from C++ and matrix `R( 1:3, 1:3 ) / -R( 4, 4 )`. These matrices absolutely identical for one incoming dataset!
I confused about order of coordinates after applying eigenvalues methods. I tried to obtain those matrices with different **online calculators**, but result was the same - the **order was various**.  I think this is the main issue what is the order we should suppose as right. 
At that time I am searching the criteria of true eigenvalues calculation.

**Comment by YuriiHordiienko1987** [comment]
Please, tell me about your translation. How did you get it? Did you use Matlab Codegen software? I thought, maybe there is a right way to translate matlab code to c++ and see the result.

**Comment by BenjaminNavarro** [comment]
I didn't use any codegen and did the translation myself since I'm quite comfortable with the Eigen library.

There's no one true eigen values computation algorithm, either their values are in seemingly random order or sorted afterwards. That's why I'm very skeptical about using these values for the radii computation. As soon as I have a Matlab license at hand and some free time, I'll check if in some cases the Matlab version can also get the radii in the wrong order, which I strongly expect, especially in the unconstrained case.

**Comment by BenjaminNavarro** [comment]
Ok so I ran some tests with Matlab and my expectations were right, there is no guarantee on the radii order.

Here is my test script (inspired by the *test_ellipsoid_fit.m* script from the Matlab package):
```matlab
eps = 1e-9;
for i = 1:100
    % radii
    a = rand();
    b = rand();
    c = rand();
    [ s, t ] = meshgrid( 0 : 0.1 : pi, 0 : 0.3 : pi );
    x = a * cos(s) .* cos( t );
    y = b * cos(s) .* sin( t );
    z = c * sin(s);
    % rotation
    ang = (rand() - 0.5) * 2 *pi;
    xt = x * cos( ang ) - y * sin( ang );
    yt = x * sin( ang ) + y * cos( ang );
    % translation
    shiftx = rand();
    shifty = rand();
    shiftz = rand();
    x = xt + shiftx;
    y = yt + shifty;
    z = z  + shiftz;
    x = x(:);
    y = y(:);
    z = z(:);
    
    % do the fitting
    [ center, radii, evecs, v, chi2 ] = ellipsoid_fit( [ x y z ], '' );
    
    if(a - radii(1)) > eps || (b - radii(2)) > eps || (c - radii(3) > eps) 
        fprintf("At iteration #%d: ", i)
        disp("Incorrect radii, expecting")
        disp([a b c])
        disp("got")
        disp(radii')
        break
    end
end
```

And it fails in most cases on the first iteration with an error like:
```
At iteration #1: Incorrect radii, expecting
    0.7522    0.8271    0.7814
got
    0.8271    0.7814    0.7522
```

Same problem, correct values in incorrect order.

I'm closing this issue since there is no implementation problem. I'll update the readme to highlight the problem and see if I can find an alternative algorithm, or a fix to this one, to solve the issue.

**Comment by YuriiHordiienko1987** [comment]
Hello Benjamin!
I applied your library successfully to my issue, thanks! Now, I would like
to get a dip angle from 3d magnetic sensor. For that I need to find
rotation matrix of ellipsoid into space due to three angles. These angles
related to X Y Z can be found with eigenvectors. So I tried to use
solver.eigevector() method for that, but I absolutely stucked what
certainly I should get as angles. Could you give an advice or may be some
code snippet to get ellipsoid angles into the space using the eigen library.
Thanks,
Best regards, Yurii

**Comment by BenjaminNavarro** [comment]
Can you please open a new issue since this is unrelated to this one?
